### ISSUE TITLE
.waves-effect doesn't work with sass

### ISSUE THREAD

**Issue by susheelk** [InfomediaLtd/angular2-materialize#320]
I'm trying to create an angular2 application with materializecss, but the .waves-effect does not work when extended using sass.
Here is my angular.cli.json:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "todolist-front"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/hammerjs/hammer.js",
        "../node_modules/materialize-css/dist/js/materialize.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

Here is my styles.scss:
```scss
$roboto-font-path: "../node_modules/materialize-css/dist/fonts/roboto/";
@import "../node_modules/materialize-css/sass/materialize";

button {
  @extend .waves-effect, .btn; // .waves-effect is extended as seen
}
```

Here is my component html:
```html
  <button class="waves-effect">Waves effect works here</button>
  <button>Waves effect doesnt work here</button>
```
As seen, the waves effect works with the first button but not the second, even though .waves-effect is extended in styles.scss. To be clear, extending other classes such as .btn work perfectly fine. Please help me in solving this. 

Thanks
